import type {MemberTypes} from "@/types/features/member.type";

export const mockMembers: MemberTypes.Service.MemberData[] = [
  {
    id: "usr_a1b2c3d4e1",
    name: "Andika Pratama",
    email: "andika.pratama@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_b2c3d4e5f2",
    name: "Naila Maulida",
    email: "naila.maulida@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_c3d4e5f6g3",
    name: "Fikri Ramdhan",
    email: "fikri.ramdhan@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_d4e5f6g7h4",
    name: "Cintya Oktaviani",
    email: "cintya.oktaviani@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_e5f6g7h8i5",
    name: "Farhan Hidayat",
    email: "farhan.hidayat@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_f6g7h8i9j6",
    name: "Melati Kusumawati",
    email: "melati.kusumawati@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_g7h8i9j0k7",
    name: "Rafli Mahardika",
    email: "rafli.mahardika@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_h8i9j0k1l8",
    name: "Salsabila Putri",
    email: "salsabila.putri@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_i9j0k1l2m9",
    name: "Roni Kurniawan",
    email: "roni.kurniawan@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_j0k1l2m3n0",
    name: "Novi Anggraeni",
    email: "novi.anggraeni@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },

  {
    id: "usr_k1l2m3n4o1",
    name: "Adnan Fadhil",
    email: "adnan.fadhil@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_l2m3n4o5p2",
    name: "Shafira Azahra",
    email: "shafira.azahra@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_m3n4o5p6q3",
    name: "Leonardo Pramudya",
    email: "leonardo.pramudya@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_n4o5p6q7r4",
    name: "Mira Rahmadani",
    email: "mira.rahmadani@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_o5p6q7r8s5",
    name: "Kevin Syahputra",
    email: "kevin.syahputra@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_p6q7r8s9t6",
    name: "Nadya Azzahra",
    email: "nadya.azzahra@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_q7r8s9t0u7",
    name: "Arif Setiawan",
    email: "arif.setiawan@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_r8s9t0u1v8",
    name: "Silvia Marlina",
    email: "silvia.marlina@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_s9t0u1v2w9",
    name: "Wisnu Prakoso",
    email: "wisnu.prakoso@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_t0u1v2w3x0",
    name: "Laras Putri",
    email: "laras.putri@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
];
