import type {UserTypes} from "@/types/features/user.type";

export const mockUsers: UserTypes.Service.UserData[] = [
  {
    id: "usr_1a2b3c4d5e",
    name: "Ahmad Fauzi",
    email: "ahmad.fauzi@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_2f3g4h5i6j",
    name: "Siti Nurhaliza",
    email: "siti.nurhaliza@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_3k4l5m6n7o",
    name: "Budi Santoso",
    email: "budi.santoso@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_4p5q6r7s8t",
    name: "Dewi Lestari",
    email: "dewi.lestari@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_5u6v7w8x9y",
    name: "Rizki Pratama",
    email: "rizki.pratama@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_6z7a8b9c0d",
    name: "Indah Permata",
    email: "indah.permata@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_7e8f9g0h1i",
    name: "Hendra Wijaya",
    email: "hendra.wijaya@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_8j9k0l1m2n",
    name: "Maya Kusuma",
    email: "maya.kusuma@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_9o0p1q2r3s",
    name: "Doni Firmansyah",
    email: "doni.firmansyah@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
  {
    id: "usr_0t1u2v3w4x",
    name: "Rina Marlina",
    email: "rina.marlina@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
  },
];
